FROM python:3.7

WORKDIR /app

COPY main.py main.py
COPY test.png test.png

RUN apt update
RUN apt install -y libgl1-mesa-glx libgeos-dev
RUN pip install paddlepaddle paddleocr fastapi uvicorn python-multipart
RUN paddleocr --image_dir ./test.png --use_angle_cls true --lang ch --use_gpu false
RUN paddleocr --image_dir ./test.png --use_angle_cls true --lang en --use_gpu false

EXPOSE 8000
CMD uvicorn main:app --host 0.0.0.0